[template]
src = "traefik.toml.tmpl"
dest = "/etc/traefik/traefik.toml"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0640"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/bin/systemctl restart traefik || /bin/systemctl start traefik"
